"""Add chat tracking fields

Revision ID: f0af18ee5eb2
Revises: 8eb8e6503a26
Create Date: 2026-02-08 01:03:25.494657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0af18ee5eb2'
down_revision: Union[str, None] = '8eb8e6503a26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('telegram_message_id', sa.BigInteger(), nullable=True))
    op.add_column('chat_messages', sa.Column('is_read', sa.Boolean(), nullable=False))
    op.add_column('chat_messages', sa.Column('sender_name', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('username', sa.String(length=255), nullable=True))
    op.add_column('leads', sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('unread_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'unread_count')
    op.drop_column('leads', 'last_message_at')
    op.drop_column('leads', 'username')
    op.drop_column('chat_messages', 'sender_name')
    op.drop_column('chat_messages', 'is_read')
    op.drop_column('chat_messages', 'telegram_message_id')
    # ### end Alembic commands ###
