"""Add lead converted_to_project_id

Revision ID: fb5fccecef48
Revises: 4a9a1f7f4004
Create Date: 2026-02-08 16:43:35.327930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5fccecef48'
down_revision: Union[str, None] = '4a9a1f7f4004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('converted_to_project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'leads', 'projects', ['converted_to_project_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_projects_foreman_id'), 'projects', ['foreman_id'], unique=False)
    op.drop_constraint('projects_foreman_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['foreman_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_foreman_id_fkey', 'projects', 'users', ['foreman_id'], ['id'])
    op.drop_index(op.f('ix_projects_foreman_id'), table_name='projects')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'converted_to_project_id')
    # ### end Alembic commands ###
