"""add_ai_infrastructure_v2

Revision ID: dec010cd2037
Revises: 8fe123994ceb
Create Date: 2026-02-08 17:23:47.390053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'dec010cd2037'
down_revision: Union[str, None] = '8fe123994ceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('knowledge_base',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_base_id'), 'knowledge_base', ['id'], unique=True)
    op.create_index(op.f('ix_knowledge_base_org_id'), 'knowledge_base', ['org_id'], unique=False)
    op.create_table('prompt_configs',
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('handoff_criteria', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_configs_id'), 'prompt_configs', ['id'], unique=True)
    op.create_index(op.f('ix_prompt_configs_org_id'), 'prompt_configs', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_configs_org_id'), table_name='prompt_configs')
    op.drop_index(op.f('ix_prompt_configs_id'), table_name='prompt_configs')
    op.drop_table('prompt_configs')
    op.drop_index(op.f('ix_knowledge_base_org_id'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_id'), table_name='knowledge_base')
    op.drop_table('knowledge_base')
    # ### end Alembic commands ###
