"""sync_lead_statuses

Revision ID: 4a9a1f7f4004
Revises: 528438071e09
Create Date: 2026-02-08 14:37:44.739315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a9a1f7f4004'
down_revision: Union[str, None] = '528438071e09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual handles for Postgres ENUM updates
    op.execute("COMMIT")
    op.execute("ALTER TYPE lead_status ADD VALUE 'CONSULTING'")
    op.execute("ALTER TYPE lead_status ADD VALUE 'FOLLOW_UP'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual removal of enum values is not supported by Postgres without recreating the type
    pass
    # ### end Alembic commands ###
