"""add telegram user bots table

Revision ID: e3f4a5b6c7d8
Revises: d27d01c8eb57
Create Date: 2026-04-04 21:25:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e3f4a5b6c7d8'
down_revision: Union[str, None] = 'd27d01c8eb57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Check if table exists before creating to prevent DuplicateTableError
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'telegram_user_bots' not in inspector.get_table_names():
        op.create_table('telegram_user_bots',
        sa.Column('org_id', sa.UUID(), nullable=False),
        sa.Column('phone', sa.String(length=50), nullable=False),
        sa.Column('api_id', sa.Integer(), nullable=True),
        sa.Column('api_hash', sa.String(length=255), nullable=True),
        sa.Column('session_string', sa.Text(), nullable=True),
        sa.Column('is_authorized', sa.Boolean(), nullable=True, default=False),
        sa.Column('is_active', sa.Boolean(), nullable=True, default=False),
        sa.Column('status', sa.String(length=50), nullable=True, default='disconnected'),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('org_id')
        )
        op.create_index(op.f('ix_telegram_user_bots_id'), 'telegram_user_bots', ['id'], unique=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_user_bots_id'), table_name='telegram_user_bots')
    op.drop_table('telegram_user_bots')
    # ### end Alembic commands ###
