"""Add AI qualification fields to Lead

Revision ID: 528438071e09
Revises: f0af18ee5eb2
Create Date: 2026-02-08 12:03:41.516940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '528438071e09'
down_revision: Union[str, None] = 'f0af18ee5eb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('ai_qualification_status', sa.String(length=50), nullable=False))
    op.add_column('leads', sa.Column('extracted_data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'extracted_data')
    op.drop_column('leads', 'ai_qualification_status')
    # ### end Alembic commands ###
