"""Add lead converted_to_project_id

Revision ID: fb5fccecef48
Revises: 4a9a1f7f4004
Create Date: 2026-02-08 16:43:35.327930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5fccecef48'
down_revision: Union[str, None] = '4a9a1f7f4004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Add column safely
    op.execute('ALTER TABLE leads ADD COLUMN IF NOT EXISTS converted_to_project_id UUID')

    # 2. Add FK for leads.converted_to_project_id
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'leads_converted_to_project_id_fkey') THEN
                ALTER TABLE leads ADD CONSTRAINT leads_converted_to_project_id_fkey 
                FOREIGN KEY (converted_to_project_id) REFERENCES projects (id) ON DELETE SET NULL;
            END IF;
        END
        $$;
    """)

    # 3. Create index safely
    op.execute('CREATE INDEX IF NOT EXISTS ix_projects_foreman_id ON projects (foreman_id)')

    # 4. Drop old FK constraint safely
    op.execute('ALTER TABLE projects DROP CONSTRAINT IF EXISTS projects_foreman_id_fkey')

    # 5. Create new FK on projects(foreman_id)
    # We use a specific name to be idempotent
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'projects_foreman_id_new_fkey') THEN
                ALTER TABLE projects ADD CONSTRAINT projects_foreman_id_new_fkey 
                FOREIGN KEY (foreman_id) REFERENCES users (id) ON DELETE SET NULL;
            END IF;
        END
        $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_foreman_id_fkey', 'projects', 'users', ['foreman_id'], ['id'])
    op.drop_index(op.f('ix_projects_foreman_id'), table_name='projects')
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'converted_to_project_id')
    # ### end Alembic commands ###
